// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestVSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "TestVSIXProject1.a1f18f18-32cc-4df3-8e28-4b7f1c70415c";
        public const string Name = "TestVSIXProject1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Kris Cavitt";
        public const string Tags = "";
    }
}
